# Taller Práctico de Pandas y Numpy

## Objetivo: 

Aplicar operaciones con Pandas y Numpy para analizar datos de Pokémon.

## Instrucciones  

- **Solo se recibirán archivos de extensión ```.ipynb```.**
- **Solo se recibiran archivos cargados en la siguiente [carpeta de drive](https://drive.google.com/drive/folders/1kKMUQDvQXwZfyEtDGkrr1HcnX7zsH5AW?usp=sharing)** _(archivos enviados directo al correo, discord u otro medio NO seran tenidos en cuenta)_
- **En el archivo ```data_info.ipynb``` se encuentra la descripción del conjunto de datos.**
- **El taller puede ser resuelto máximo en grupos de 3 personas. Solo subir un archivo por grupo.**
- **Mencionar los integrantes del grupo en la celda que se encuentra en la perte inferior.**


- **_Fecha máxima de entrega: 03 de abril de 2025_**

---

In [ ]:
### Integrantes (nombres completos):

# Joan Daniel Giraldo Quintero

## Parte 1: Exploración de Datos con Pandas  

1. Carga el dataset en un DataFrame de Pandas.


In [ ]:
import pandas as pd 

df = pd.read_csv(r"C:\Users\user\OneDrive\Desktop\BOOTCAMP\BOOT\Taller-jupyter-numpy\Pokemon.csv")

df.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

2. Muestra las primeras 5 filas del dataset.

In [ ]:
df.head(5)

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

3. ¿Cuántos valores nulos hay en cada columna?

In [ ]:
df.isnull().sum()

#             0
Name          0
Type 1        0
Type 2        0
Total         0
HP            0
Attack        0
Defense       0
Sp. Atk       0
Sp. Def       0
Speed         0
Generation    0
Legendary     0
Poderoso      0
dtype: int64

4. Reemplaza los valores nulos en la columna `Type 2` por `"Unknown"`.

In [ ]:
df["Type 2"] = df["Type 2"].fillna("Unknown")

5. ¿Cuántos Pokémon hay de cada tipo principal (`Type 1`)? 

In [ ]:
conteo_principal = df["Type 1"].value_counts()
conteo_principal

Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Rock         44
Electric     44
Ground       32
Ghost        32
Dragon       32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64

6. ¿Cuántos Pokémon legendarios hay?

In [ ]:
conteo_legendarios = df["Legendary"].value_counts()
conteo_legendarios

## Hay 65 pokemones legendarios

Legendary
False    735
True      65
Name: count, dtype: int64

7. Obtén el promedio de cada estadística de combate (`HP`, `Attack`, `Defense`, etc.). 

In [ ]:
columnas_combate = ["HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed"]
promedio_combate = df[columnas_combate].mean()

promedio_combate

HP         69.25875
Attack     79.00125
Defense    73.84250
Sp. Atk    72.82000
Sp. Def    71.90250
Speed      68.27750
dtype: float64

8. ¿Cuál es el Pokémon con la mayor velocidad (`Speed`)?

In [ ]:
Pokemon_mas_rapido= df.sort_values("Speed", ascending= False).head(1)
Pokemon_mas_rapido

#               Name   Type 1   Type 2  Total  HP  Attack  Defense  \
431  386  DeoxysSpeed Forme  Psychic  Unknown    600  50      95       90   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
431       95       90    180           3       True

9. Filtra los Pokémon de tipo `"Fire"` con ataque (`Attack`) mayor a 80.

In [ ]:
filtro_fuego_fuerte = df[(df["Type 1"] == "Fire") & (df["Attack"] > 80)]

filtro_fuego_fuerte

#                       Name Type 1    Type 2  Total   HP  Attack  \
6      6                  Charizard   Fire    Flying    534   78      84   
7      6  CharizardMega Charizard X   Fire    Dragon    634   78     130   
8      6  CharizardMega Charizard Y   Fire    Flying    634   78     104   
64    59                   Arcanine   Fire   Unknown    555   90     110   
83    77                     Ponyta   Fire   Unknown    410   50      85   
84    78                   Rapidash   Fire   Unknown    500   65     100   
135  126                     Magmar   Fire   Unknown    495   65      95   
147  136                    Flareon   Fire   Unknown    525   65     130   
158  146                    Moltres   Fire    Flying    580   90     100   
171  157                 Typhlosion   Fire   Unknown    534   78      84   
263  244                      Entei   Fire   Unknown    580  115     115   
270  250                      Ho-oh   Fire    Flying    680  106     130   
277  256                  Combusken   Fire  Fighting    405   60      85   
278  257                   Blaziken   Fire  Fighting    530   80     120   
279  257      BlazikenMega Blaziken   Fire  Fighting    630   80     160   
353  323                   Camerupt   Fire    Ground    460   70     100   
354  323      CameruptMega Camerupt   Fire    Ground    560   70     120   
355  324                    Torkoal   Fire   Unknown    470   70      85   
437  392                  Infernape   Fire  Fighting    534   76     104   
518  467                  Magmortar   Fire   Unknown    540   75      95   
542  485                    Heatran   Fire     Steel    600   91      90   
558  499                    Pignite   Fire  Fighting    418   90      93   
559  500                     Emboar   Fire  Fighting    528  110     123   
573  514                   Simisear   Fire   Unknown    498   75      98   
614  554                   Darumaka   Fire   Unknown    315   70      90   
615  555    DarmanitanStandard Mode   Fire   Unknown    480  105     140   
692  631                    Heatmor   Fire   Unknown    484   85      97   
731  663                 Talonflame   Fire    Flying    499   78      81   
799  721                  Volcanion   Fire     Water    600   80     110   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  
6         78      109       85    100           1      False  
7        111      130       85    100           1      False  
8         78      159      115    100           1      False  
64        80      100       80     95           1      False  
83        55       65       65     90           1      False  
84        70       80       80    105           1      False  
135       57      100       85     93           1      False  
147       60       95      110     65           1      False  
158       90      125       85     90           1       True  
171       78      109       85    100           2      False  
263       85       90       75    100           2       True  
270       90      110      154     90           2       True  
277       60       85       60     55           3      False  
278       70      110       70     80           3      False  
279       80      130       80    100           3      False  
353       70      105       75     40           3      False  
354      100      145      105     20           3      False  
355      140       85       70     20           3      False  
437       71      104       71    108           4      False  
518       67      125       95     83           4      False  
542      106      130      106     77           4       True  
558       55       70       55     55           5      False  
559       65      100       65     65           5      False  
573       63       98       63    101           5      False  
614       45       15       45     50           5      False  
615       55       30       55     95           5      False  
692       66      105    

10. Crea una nueva columna que indique si un Pokémon tiene una estadística total (`Total`) mayor al promedio.  

In [ ]:
Promedio= df["Total"].mean()

df["Poderoso"]= df["Total"] > Promedio

df.head()

#                   Name Type 1   Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass   Poison    318  45      49       49   
1  2                Ivysaur  Grass   Poison    405  60      62       63   
2  3               Venusaur  Grass   Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass   Poison    625  80     100      123   
4  4             Charmander   Fire  Unknown    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  Poderoso  
0       65       65     45           1      False     False  
1       80       80     60           1      False     False  
2      100      100     80           1      False      True  
3      122      120     80           1      False      True  
4       60       50     65           1      False     False

---

## Parte 2: Análisis con Numpy  

11. Convierte las columnas de estadísticas (`HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`) en un array de Numpy.  

In [ ]:
import numpy as np

stats_pokemon= df[["HP","Attack","Defense","Sp. Atk","Sp. Def","Speed"]].to_numpy()

stats_pokemon

array([[ 45,  49,  49,  65,  65,  45],
       [ 60,  62,  63,  80,  80,  60],
       [ 80,  82,  83, 100, 100,  80],
       ...,
       [ 80, 110,  60, 150, 130,  70],
       [ 80, 160,  60, 170, 130,  80],
       [ 80, 110, 120, 130,  90,  70]], shape=(800, 6))

12. Calcula la media, mediana y desviación estándar de cada estadística usando Numpy.  

In [ ]:
media= np.mean(stats_pokemon, axis=0)
mediana=np.median(stats_pokemon, axis=0)
desviacion=np.std(stats_pokemon, axis=0)

print("media:",media)
print("mediana;", mediana)
print("desviacion:", desviacion)


media: [69.25875 79.00125 73.8425  72.82    71.9025  68.2775 ]
mediana; [65. 75. 70. 65. 70. 65.]
desviacion: [25.51870487 32.43707367 31.16400478 32.70183634 27.81151729 29.04230524]


13. Normaliza las estadísticas dividiendo cada valor por el máximo de su columna.

In [ ]:
maximos= np.max(stats_pokemon, axis= 0)

normal= stats_pokemon/maximos

normal


array([[0.17647059, 0.25789474, 0.21304348, 0.33505155, 0.2826087 ,
        0.25      ],
       [0.23529412, 0.32631579, 0.27391304, 0.41237113, 0.34782609,
        0.33333333],
       [0.31372549, 0.43157895, 0.36086957, 0.51546392, 0.43478261,
        0.44444444],
       ...,
       [0.31372549, 0.57894737, 0.26086957, 0.77319588, 0.56521739,
        0.38888889],
       [0.31372549, 0.84210526, 0.26086957, 0.87628866, 0.56521739,
        0.44444444],
       [0.31372549, 0.57894737, 0.52173913, 0.67010309, 0.39130435,
        0.38888889]], shape=(800, 6))

14. Encuentra los índices de los 5 Pokémon con mayor defensa (`Defense`).  

In [ ]:
Defensa= stats_pokemon[:,2]
indices_ordenados=np.argsort(Defensa)

top_5_indices_mas_duros= indices_ordenados[-5:][::-1]

top_5_indices_mas_duros

array([333, 224, 230, 414, 223])

15. Calcula la correlación entre `Attack` y `Defense`.

In [ ]:
Ataque= stats_pokemon[:,1]
Defensa1=stats_pokemon[:,2]

Correlacion= np.corrcoef(Ataque, Defensa1)

Correlacion

array([[1.        , 0.43868706],
       [0.43868706, 1.        ]])

16. Usa Numpy para encontrar cuántos Pokémon tienen una suma de (`HP`, `Attack` y `Defense`) superior a 300.

In [ ]:
Columnas=stats_pokemon[:,0:3]
Suma=np.sum(Columnas, axis=1)

Pokemones_superiores=np.sum(Suma > 300)

Pokemones_superiores

np.int64(94)